### ISSUE TITLE
Inline Range Calendar Doesn't Show Range Selection

### ISSUE THREAD

**Issue by mtderryberry** [SaturnTeam/saturn-datepicker#89]
The inline range calendar (as shown in the online demo) does not show the selected range as expected. Once the first date is selected, the range selection is shown on hover, but once the second date is selected, the range selection does not stay. This causes it to look like only a single date is selected. This is reproducible in the online demo (https://stackblitz.com/edit/angular-4cfnyl?file=src%2Fapp%2Fapp.component.html)

**Comment by SaturnTeam** [comment]
@beyondsanity

**Comment by theonelucas** [comment]
This error is due to:

https://github.com/SaturnTeam/saturn-datepicker/blob/a44856c56bf02b3af1d6dbd01fdd984f74ce03be/saturn-datepicker/src/datepicker/calendar.ts#L428

And fixed in https://github.com/SaturnTeam/saturn-datepicker/pull/88

**Comment by NicolasRigo** [comment]
Dear SaturnTeam, 

This error is still present in 8.0.1 (Inline Range Calendar Doesn't Show Range Selection)

Regards

**Comment by beyondsanity** [comment]
@NicolasRigo what browser are you using? I can't replicate this issue, even the linked demo seems to be working.

**Comment by NicolasRigo** [comment]
> @NicolasRigo what browser are you using? I can't replicate this issue, even the linked demo seems to be working.

@beyondsanity It's working now. To be honest, I apparently made a mistake by importing CSS at component level. It works by importing CSS in global styles.

And it's working quite well BTW ...

**Comment by beyondsanity** [comment]
@SaturnTeam I think the issue can be closed
